### PR TITLE
Issue #35: Make ETARC compound FKs DEFERRABLE INITIALLY IMMEDIATE

### LINKED ISSUE #35: ETP-3621: Partition Key Update Blocked by Non-Deferrable Compound FKs
# Error's description

When a table is partitioned by ETARC (e.g., c_orderline partitioned by dateordered), updating the partition key column on existing rows fails due to PostgreSQL's partition row movement mechanism. PostgreSQL implements partition key changes as an internal DELETE + INSERT, which is blocked by:

ETARC creates compound FKs on child tables with the pattern FOREIGN KEY (fk_col, etarc_helper_col) REFERENCES parent_table(pk, partition_key). These FKs are created as NOT DEFERRABLE, so the internal DELETE is immediately rejected by ON DELETE NO ACTION constraints, or worse, ON DELETE CASCADE constraints silently delete child rows.

In practice, this means the partition key of any ETARC-partitioned table becomes immutable after insert if the table has child relationships ? any attempt to update it results in FK violations or data loss via cascading deletes.

**Real-world impact**

In MetalTech (MSM), c_orderline is partitioned by dateordered. The booking process (c_order_post) updates c_order.dateordered = TRUNC(now()), but c_orderline.dateordered cannot be updated to match because c_orderline has 91 compound FK constraints from child tables (e.g., c_orderlinetax, c_orderline_offer, m_matchpo, etc.) ? all non-deferrable. This causes a permanent date desync between order headers and their lines.

# Steps to reproduce the error
# Required Configurations

ETARC module (com.etendoerp.db.extended) installed and active
A table partitioned via ETARC using RANGE partitioning (e.g., c_orderline by dateordered)
The partitioned table must have at least one child table with a foreign key relationship (ETARC will have created compound FKs)

Steps

1. Create a record in the partitioned table (e.g., insert an order line with dateordered = '2025-11-06')
2. Ensure child records exist referencing this row (e.g., c_orderlinetax rows linked to the order line)
3. Attempt to update the partition key column to a value in a different partition:

```
UPDATE c_orderline
SET dateordered = '2026-03-30'
WHERE c_orderline_id = '<id>';
```

4. Result: FK violation from child table compound constraint:

ERROR: update or delete on table "c_orderline_y2025" violates foreign key constraint
"etarc_c_orderlinetax_c_orderline" on table "c_orderlinetax"
DETAIL: Key (c_orderline_id, dateordered)=(<id>, 2025-11-06) is still referenced
from table "c_orderlinetax".

Even if child FKs are updated first, self-referencing FKs on the same table (e.g., c_orderline parent line references) also block the operation because constraints are validated row-by-row, not at transaction end.

# Expected behavior

It should be possible to update the partition key column on ETARC-partitioned tables when necessary. The compound FK constraints should support deferred validation so that partition row movement (internal DELETE + INSERT) can complete within a transaction, with FK integrity validated at commit time.

Specifically:

- ETARC should create compound FKs as DEFERRABLE INITIALLY IMMEDIATE instead of the current non-deferrable default
- A mechanism should exist to update helper columns on child tables when the parent's partition key changes

Affected Version
Module: com.etendoerp.db.extended (ETARC)
Version: Latest (as of 2026-03-30)

# Solution Design (optional)
**Option A: Make compound FKs DEFERRABLE (recommended)**
Change the FK creation template in SqlBuilder.java (~line 92-97):

// Current:
```
private static final String ADD_FK_PARTITIONED =
    "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s, %s) " +
        "REFERENCES PUBLIC.%s (%s, %s) MATCH SIMPLE ON UPDATE CASCADE ON DELETE %s;\n";
```

// Proposed:
```
private static final String ADD_FK_PARTITIONED =
    "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s, %s) " +
        "REFERENCES PUBLIC.%s (%s, %s) MATCH SIMPLE ON UPDATE CASCADE ON DELETE %s " +
        "DEFERRABLE INITIALLY IMMEDIATE;\n";
```

DEFERRABLE INITIALLY IMMEDIATE preserves current behavior (constraints checked immediately by default) but allows callers to SET CONSTRAINTS ALL DEFERRED when they need to perform partition key updates. This is a **non-breaking change.**

A migration script or modulescript would be needed to recreate existing compound FKs as DEFERRABLE on systems that already ran update.database.

**Option B: ETARC-managed partition key update function**
ETARC could provide a utility PL/pgSQL function that:
1. Sets constraints to deferred
2. Updates all helper columns on child tables (discoverable via pg_constraint)
3. Updates the partition key on the parent row
4. Lets the transaction commit validate FK integrity

### PR DESCRIPTION
**Pull request by RomanMagnoli**
## Summary

- ETARC compound FKs (those referencing partitioned tables with an `etarc_*` helper column) were created as `NOT DEFERRABLE`, making the partition key column effectively immutable after insert.
- Updated `SqlBuilder.java` to create new compound FKs as `DEFERRABLE INITIALLY IMMEDIATE`.
- Added `MakeEtarcFksDeferrable` migration ModuleScript to recreate existing non-deferrable compound FKs on already-updated installations.

## Test plan

- [ ] Partition a table via ETARC (e.g. `c_orderline` by `dateordered`)
- [ ] Verify new compound FKs are created as `DEFERRABLE INITIALLY IMMEDIATE` after `update.database`
- [ ] On an existing installation, run `update.database` and verify `MakeEtarcFksDeferrable` migrates existing FKs to deferrable
- [ ] Confirm that updating the partition key column within a transaction using `SET CONSTRAINTS ALL DEFERRED` no longer raises FK violations
- [ ] Confirm that normal FK enforcement (immediate mode) still works as expected

Fixes #35 | ETP-3621

### CODE REVIEW

File: src-util/modulescript/src/com/etendoerp/db/extended/utils/SqlBuilder.java [hunk 1]
```diff
@@ -89,9 +89,12 @@ public class SqlBuilder {
...
       "UPDATE %s SET %s = F.%s FROM %s F WHERE F.%s = %s.%s AND %s.%s IS NULL;\n";
   // ON DELETE action is now dynamic (last %s). ON UPDATE remains CASCADE (partitioned) or NO ACTION (simple) per existing behavior.
+  // DEFERRABLE INITIALLY IMMEDIATE allows callers to SET CONSTRAINTS ALL DEFERRED when performing
+  // partition key updates (which PostgreSQL implements as DELETE + INSERT internally). ETP-3621.
   private static final String ADD_FK_PARTITIONED =
       "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s, %s) " +
-          "REFERENCES PUBLIC.%s (%s, %s) MATCH SIMPLE ON UPDATE CASCADE ON DELETE %s;\n";
+          "REFERENCES PUBLIC.%s (%s, %s) MATCH SIMPLE ON UPDATE CASCADE ON DELETE %s " +
+          "DEFERRABLE INITIALLY IMMEDIATE;\n";
   private static final String ADD_FK_SIMPLE =
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/utils/SqlBuilder.java:98]: **Suggestion**

The implementation is correct and aligns with the requirements for ETP-3621. No changes needed.

```java
"DEFERRABLE INITIALLY IMMEDIATE;\n";
```

**Rationale**: The implementation correctly adds DEFERRABLE INITIALLY IMMEDIATE to foreign key constraints for partitioned tables. This is a best practice in PostgreSQL when dealing with partitioning, as it allows for deferring constraint checks during partition key updates (which are processed as DELETE + INSERT operations). Without this, such updates could cause immediate constraint violations.

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+            .append(" FOREIGN KEY (").append(fk.childCols).append(")")
+            .append(" REFERENCES PUBLIC.").append(fk.parentTable)
+            .append(" (").append(fk.parentCols).append(")")
+            .append(" MATCH SIMPLE ON UPDATE CASCADE ON DELETE ").append(fk.onDeleteAction)
+            .append(" DEFERRABLE INITIALLY IMMEDIATE;\n");
+      }
+
+      String sql = migrationSql.toString();
+      try (PreparedStatement ps = cp.getPreparedStatement(sql)) {
+        ps.executeUpdate();
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java]: **[RESOLVED]**  > [!WARNING]
**⚠️ Blocking Issue**

Execute each ALTER TABLE statement individually inside the loop instead of building a single string with all statements.

```java
for (FkInfo fk : fks) {
  String dropSql = "ALTER TABLE " + fk.childTable + " DROP CONSTRAINT IF EXISTS " + fk.fkName;
  try (PreparedStatement ps = cp.getPreparedStatement(dropSql)) {
    ps.executeUpdate();
  }
  String addSql = "ALTER TABLE " + fk.childTable + 
      " ADD CONSTRAINT " + fk.fkName + 
      " FOREIGN KEY (" + fk.childCols + ")" + 
      " REFERENCES " + fk.parentTable + " (" + fk.parentCols + ")" + 
      " MATCH SIMPLE ON UPDATE CASCADE ON DELETE " + fk.onDeleteAction + 
      " DEFERRABLE INITIALLY IMMEDIATE";
  try (PreparedStatement ps = cp.getPreparedStatement(addSql)) {
    ps.executeUpdate();
  }
}
```

**Rationale**: PreparedStatement and executeUpdate are designed to handle a single SQL statement. Concatenating multiple statements separated by semicolons in one execution is unreliable and not supported by default in most Etendo environments, which can lead to silent failures or incomplete migrations.

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+      for (FkInfo fk : fks) {
+        log4j.info("ETP-3621: Migrating FK {} on table {}.", fk.fkName, fk.childTable);
+        migrationSql
+            .append("ALTER TABLE ").append(fk.childTable)
+            .append(" DROP CONSTRAINT IF EXISTS ").append(fk.fkName).append(";\n")
+            .append("ALTER TABLE ").append(fk.childTable)
+            .append(" ADD CONSTRAINT ").append(fk.fkName)
+            .append(" FOREIGN KEY (").append(fk.childCols).append(")")
+            .append(" REFERENCES PUBLIC.").append(fk.parentTable)
+            .append(" (").append(fk.parentCols).append(")")
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java]: **Suggestion**

Avoid hardcoding the PUBLIC. schema prefix. If a prefix is required, use lowercase 'public.' or ensure it is dynamically retrieved.

```java
.append(" REFERENCES ").append(fk.parentTable)
```

**Rationale**: In PostgreSQL, the default schema is lowercase 'public'. 'PUBLIC' is a reserved keyword for the role encompassing all users. Hardcoding a schema prefix (especially in uppercase) reduces the script's flexibility and may fail if the database uses a non-standard schema configuration. Etendo usually relies on the search_path.

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java [hunk 4]
```diff
@@ -0,0 +1,174 @@
...
+
+      log4j.info("ETP-3621: Found {} non-deferrable ETARC compound FK(s) to make DEFERRABLE INITIALLY IMMEDIATE.",
+          fks.size());
+
+      StringBuilder migrationSql = new StringBuilder();
+      for (FkInfo fk : fks) {
+        log4j.info("ETP-3621: Migrating FK {} on table {}.", fk.fkName, fk.childTable);
+        migrationSql
+            .append("ALTER TABLE ").append(fk.childTable)
+            .append(" DROP CONSTRAINT IF EXISTS ").append(fk.fkName).append(";\n")
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java]: **Suggestion**

Consider quoting database identifiers using double quotes.

```java
.append("ALTER TABLE \"").append(fk.childTable).append("\"")
```

**Rationale**: Quoting identifiers (table names, constraint names, column names) is a best practice in SQL scripts to handle mixed-case names or names that might conflict with reserved keywords.

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+  private String mapConfDelType(String confdeltype) {
+    if (confdeltype == null) {
+      return "NO ACTION";
+    }
+    switch (confdeltype) {
+      case "c": return "CASCADE";
+      case "n": return "SET NULL";
+      case "r": return "RESTRICT";
+      case "a":
+      default:  return "NO ACTION";
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java:164]: **Suggestion**

Add a mapping for the 'SET DEFAULT' action (character 'd' in confdeltype).

```java
case "d": return "SET DEFAULT";
      case "a":
```

**Rationale**: The PostgreSQL confdeltype 'd' corresponds to the 'SET DEFAULT' action, which is currently unmapped in the script. Adding it ensures the script correctly handles all potential foreign key delete actions.

**Review by etendobot — CHANGES_REQUESTED** [review]
Changes requested by agent. Please resolve blocking issues.

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java (hunk 3 above)
Comment (RomanMagnoli) [reply src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java]: /false-positive

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java (hunk 4 above)
Comment (RomanMagnoli) [reply src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java]: /false-positive

File: src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+      log4j.info("ETP-3621: Found {} non-deferrable ETARC compound FK(s) to make DEFERRABLE INITIALLY IMMEDIATE.",
+          fks.size());
+
+      for (FkInfo fk : fks) {
+        log4j.info("ETP-3621: Migrating FK {} on table {}.", fk.fkName, fk.childTable);
+
+        String dropSql = "ALTER TABLE " + fk.childTable
+            + " DROP CONSTRAINT IF EXISTS " + fk.fkName;
+        try (PreparedStatement ps = cp.getPreparedStatement(dropSql)) {
+          ps.executeUpdate();
```
Comment (etendobot) [inline src-util/modulescript/src/com/etendoerp/db/extended/modulescript/MakeEtarcFksDeferrable.java:106]: **Suggestion**

Consider using ConnectionProvider.releasePreparedStatement() in a finally block instead of try-with-resources for the PreparedStatement to ensure the connection is returned to the pool.

```java
        PreparedStatement ps = null;
        try {
          ps = cp.getPreparedStatement(dropSql);
          ps.executeUpdate();
        } finally {
          cp.releasePreparedStatement(ps);
        }
```

**Rationale**: In Etendo's ConnectionProvider implementation, getPreparedStatement(sql) typically acquires a connection from the pool. While try-with-resources closes the statement, it may not return the connection to the pool unless releasePreparedStatement() is explicitly called, potentially leading to connection leaks when executed in a loop. Although this follows previous suggestions, using releasePreparedStatement is the safer pattern in the Etendo framework.

**Review by etendobot — APPROVED** [review]

File: pipelines/Jenkinsfile [hunk 7]
```diff
@@ -31,7 +31,7 @@ pipeline {
     COMMIT_AUTHOR_NAME  = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
     COMMIT_AUTHOR_EMAIL = sh(returnStdout: true, script: "git log -1 --pretty=format:'%ae'").trim()
 
-    JAVA_HOME           = '/usr/lib/jvm/java-11-openjdk-amd64'
+    JAVA_HOME           = '/usr/lib/jvm/java-17-openjdk-amd64'
     BUILD_CLASSIC       = true
```
Comment (etendobot) [inline pipelines/Jenkinsfile:35]: **Suggestion**

The upgrade to Java 17 is correct for Etendo 25. Verify that the Jenkins build agents are configured with the OpenJDK 17 package at this specific path.

```groovy
    JAVA_HOME           = '/usr/lib/jvm/java-17-openjdk-amd64'
```

**Rationale**: Updating the Java version to 17 is required for compatibility with Etendo 25. This change ensures the build environment matches the recommended software stack.

File: pipelines/Jenkinsfile [hunk 8]
```diff
@@ -180,7 +180,7 @@ spec:
                     githubUser=${GITHUB_USER}\n
                     githubToken=${GITHUB_TOKEN}\n
                     allow.root=true\n
-                    java.version=11\n
+                    java.version=17\n
                     org.gradle.daemon=false\n
```
Comment (etendobot) [inline pipelines/Jenkinsfile:184]: **Suggestion**

Updating java.version to 17 is consistent with the environment upgrade. Note that while java.version is not a standard Etendo Gradle property, it is useful for custom build logic or reporting within the pipeline.

```groovy
                    java.version=17\n
```

**Rationale**: Aligns the generated gradle.properties with the updated environment Java version.

**Review by etendobot — APPROVED** [review]

**Review by etendobot — DISMISSED** [review]
Changes requested by agent. Please resolve blocking issues.
